// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestrictRService.Models;

public partial class BlockedWebsiteUrl
{
    public long BlockedSitesUrlsId { get; set; }

    public long BlockedSitesId { get; set; }

    public string Url { get; set; }

    public virtual BlockedWebsite BlockedSites { get; set; }
}