// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestrictRService.Models;

public partial class BlockedWebsite
{
    public long BlockedSitesId { get; set; }

    public long EventId { get; set; }

    public long BlockAllSites { get; set; }

    public virtual ICollection<BlockedWebsiteUrl> BlockedWebsiteUrls { get; set; } = new List<BlockedWebsiteUrl>();

    public virtual Event Event { get; set; }
}