// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestrictRService.Models;

public partial class Event
{
    public long EventId { get; set; }

    public string Start { get; set; }

    public string Duration { get; set; }

    public long Recurrence { get; set; }

    public virtual ICollection<BlockedApplication> BlockedApplications { get; set; } = new List<BlockedApplication>();

    public virtual ICollection<BlockedWebsite> BlockedWebsites { get; set; } = new List<BlockedWebsite>();
}